services:
  api:
    build:
      context: .  # Chọn context nơi chứa toàn bộ mã nguồn , dấu . sẽ tìm CÁC FOLDER bên trong JMSBackend (thư mục chứa mã nguồn)
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"
      # - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+443;http://+:80
      # - ASPNETCORE_HTTPS_PORT=5001
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=JMS_BE;User Id=sa;Password=Tri123456@;MultipleActiveResultSets=true;TrustServerCertificate=True
    depends_on:
      - sqlserver

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql_server
    restart: always
    environment:
      SA_PASSWORD: "Tri123456@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  sqlserver_data:
