services:
  api:
    build:
      context: .  # Chọn context nơi chứa toàn bộ mã nguồn , dấu . sẽ tìm CÁC FOLDER bên trong JMSBackend (thư mục chứa mã nguồn)
      dockerfile: API/Dockerfile
    container_name: webapi_container
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=JMS_BE;User Id=sa;Password=Tri123456@;Trusted_Connection=False;MultipleActiveResultSets=true;TrustServerCertificate=True
    depends_on:
      - sqlserver

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04"  
    container_name: sql_server
    restart: always
    environment:
      SA_PASSWORD: "Tri123456@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db:/var/opt/mssql/backup  #/docker-entrypoint-initdb.d

volumes:
  sqlserver_data:
